apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-logic
spec:
  replicas: 2
  minReadySeconds: 15
  selector:
    matchLabels:
      app: sa-logic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-logic
    spec:
      containers:
        - image: 781857/sentiment-analysis-logic:minikube2
          imagePullPolicy: Always
          name: sa-logic
          env:
          - name: SA_WEB_APP_URL
            value: "http://sa-web-app-lb:80"
          ports:
            - containerPort: 5000